version: '3'
services:
  apache:
    build: .docker/apache
    container_name: apache
    restart: always
    ports:
      - 8085:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4_apache
    depends_on:
      - php_apache

  php_apache:
    build: .docker/php
    container_name: php_apache
    restart: always
    volumes:
      - .:/home/wwwroot/sf4_apache
    environment:
      - maildev_host=maildev
    depends_on:
      - maildev

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - 8081:80

# UNIX only: get containers IP address and update host (replace IP according to your configuration) (on Windows, edit C:\Windows\System32\drivers\etc\hosts)
#$ sudo echo $(docker network inspect bridge | grep Gateway | grep -o -E '[0-9\.]+') "symfony.local" >> /etc/hosts